### ISSUE TITLE
[jsdoc] README support

### ISSUE THREAD

**Issue by phasebash** [phasebash/jsdoc3-maven-plugin#13]
Support inclusion of readme markdown files.

**Comment by M3lkior** [comment]
Thanks @jgettings.

It's also work by putting path to .md file in directoryRoots' option : 

```
<configuration>
	<directoryRoots>
                  <directoryRoot>path/to/js</directoryRoot>
		<directoryRoot>path/to/README.md</directoryRoot>
	</directoryRoots>
</configuration>
```

**Comment by phasebash** [comment]
Honestly either will work.  Source Roots and Directory Roots are just a facade over the same command line arguments to the jsdoc3 library, I provide these both to make your POMs easier to read.
