### ISSUE TITLE
Support for changing the working directory

### ISSUE THREAD

**Issue by alex-dow** [phasebash/jsdoc3-maven-plugin#21]
Apologies in advance if this isn't the right place for this problem to be fixed.

I am building a multi module maven project. A module a few levels deep is using jsdoc3-maven-plugin.

the problem is that I have jsdoc3 configured to use a template, but I can only use a relative path in that configuration. It is relative to the module's directory. So if I run mvn install on the root project instead, the working directory become's the root project's directory, and jsdoc3 fails to find the publish.js file of the template I am using.

So, like maven-exec-plugin, it would be nice if I could specifiy the working directory I want to be in before executing jsdoc.

**Comment by phasebash** [comment]
Let me know if this should not be closed, I take silence as confirmation.
