### ISSUE TITLE
Update to latest release of jsdoc3

### ISSUE THREAD

**Issue by phasebash** [phasebash/jsdoc3-maven-plugin#24]

**Comment by M3lkior** [comment]
Hello,

It's done ?

**Comment by demonfiddler** [comment]
At the time of writing the latest version of JSDoc now appears to be 3.3, which does not work with jsdoc3-maven-plugin, because the JSDoc CLI has incompatible changes since 3.2.

I have made the necessary changes to support JSDoc 3.3, simply awaiting legal approval to submit a PR.

**Comment by phasebash** [comment]
This is happening now... just need to get back into Sonatype, I've lost my keys literally about 5 times.

**Comment by phasebash** [comment]
1.2.0 is the most recent release and has this change.
